import type { VaultItem } from "./types";

// PRD §4.4 and Feature 6: curated catalog. Items aspirational, not transactional.
export const VAULT: VaultItem[] = [
  {
    id: "sas_oslo",
    title: "SAS — Stockholm → Oslo weekend",
    description: "Round-trip economy on SAS plus a 2-night Airbnb in Grünerløkka.",
    category: "travel",
    rate: "A",
    costSEK: 2400,
    imageHint: "oslo-skyline",
  },
  {
    id: "sas_barcelona",
    title: "Norwegian — Stockholm → Barcelona",
    description: "Direct flight + 3 nights in El Born. Bring trainers.",
    category: "travel",
    rate: "A",
    costSEK: 5200,
    imageHint: "barcelona-rooftops",
  },
  {
    id: "matchi_tennis_pack",
    title: "Matchi — 10-session tennis court pack",
    description: "Indoor courts across Stockholm, valid 3 months.",
    category: "experience",
    rate: "A",
    costSEK: 1900,
    imageHint: "tennis-court",
  },
  {
    id: "djurgarden_match",
    title: "Djurgården IF — home-match ticket",
    description: "Lower stand, Tele2 Arena.",
    category: "experience",
    rate: "A",
    costSEK: 480,
    imageHint: "hockey-arena",
  },
  {
    id: "escape_room",
    title: "Stockholm Escape — 4-player room",
    description: "Bring three people. Counts as social outing.",
    category: "experience",
    rate: "A",
    costSEK: 1400,
    imageHint: "escape-room",
  },
  {
    id: "sailing_archipelago",
    title: "Archipelago sailing day",
    description: "Skipper-led 6-hour sail from Saltsjöbaden.",
    category: "experience",
    rate: "A",
    costSEK: 2100,
    imageHint: "stockholm-archipelago",
  },
  {
    id: "duolingo_plus_year",
    title: "Duolingo Super — 12 months",
    description: "For the Swedish track. Streak shields included.",
    category: "learning",
    rate: "A",
    costSEK: 999,
    imageHint: "language-app",
  },
  {
    id: "adlibris_book_voucher",
    title: "Adlibris — 500 SEK book voucher",
    description: "Physical books only. No e-books.",
    category: "learning",
    rate: "A",
    costSEK: 500,
    imageHint: "book-stack",
  },
  {
    id: "lilla_ego",
    title: "Lilla Ego — dinner for two",
    description: "Sit-down. Booking 4–6 weeks out.",
    category: "food",
    rate: "A",
    costSEK: 1600,
    imageHint: "restaurant",
  },
  {
    id: "wellness_massage",
    title: "Wellness — 60-min sports massage",
    description: "Partner clinic in Vasastan.",
    category: "health",
    rate: "A",
    costSEK: 850,
    imageHint: "spa",
  },
  {
    id: "sats_day_pass_5",
    title: "SATS — 5-pack of day passes",
    description: "Use at any SATS in Stockholm.",
    category: "health",
    rate: "A",
    costSEK: 750,
    imageHint: "gym",
  },
  {
    id: "wolt_credit",
    title: "Wolt — 200 SEK credit",
    description: "Category B: applied at the 1 SEK / 180 pts rate.",
    category: "delivery",
    rate: "B",
    costSEK: 200,
    imageHint: "food-delivery",
  },
  {
    id: "amazon_credit",
    title: "Amazon — 300 SEK credit",
    description: "Category B: applied at the 1 SEK / 180 pts rate.",
    category: "shopping",
    rate: "B",
    costSEK: 300,
    imageHint: "shopping",
  },
];

export const VAULT_INDEX: Record<string, VaultItem> = Object.fromEntries(
  VAULT.map((v) => [v.id, v])
);
